# 유레카 서버의 포트번호 지정
server:
  port: 8761
  
# 마이크로서비스 애플리케이션에서 이 애플리케이션을 식별하는 이름
spring:
  application:
    name: bookstore-eureka-server
    
# 이 애플리케이션은 유레카서버이기 때문에 유레카 클라이언트로 등록시키지 않고, 레지스트리 정보를 요청하지 않는다.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    