server:
  port: 8761
 
### 마이크로서비스 아키텍처에서 이 서비스를 식별하는 아이디다.
spring:
  application:
    name: msa-eureka-server

### eureka.client.register-with-eureka
### 유레카 서버에 자기 자신을 클라이언트로 등록하지 않도록 하는 설정이다.
### 본 프로젝트는 디스커버리 서버 역할을 하는 유레카 서버이므로 자기 자신을 클라이언트로써 디스커버리 서버에 등록하지 않도록 false로 설정한다.
### eureka.client.fetch-register
### 클라이언트로써 eureka 서버에서 eureka 레지스트리 정보를 가져올지 여부를 설정한다.
### 클라이언트가 아니므로 false로 설정한다. 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false